### ISSUE TITLE
端口号必须是443端口么

### ISSUE THREAD

**Issue by neo-no93** [Acris/docker-shadowsocks-libev#19]
我想问下端口号有限制嘛, 我的一直没配置成功, 容器起来了,但是在自己电脑上shadowsocksX-NG 配上没有用

**Comment by Acris** [comment]
非必需，端口号无限制。
贴一下容器启动命令，注意敏感信息打码，我帮你排查下问题。

**Comment by neo-no93** [comment]
我是用你的那个docker-compose.yml 文件起的docker, 除了domain改了,其他都没改.

**Comment by neo-no93** [comment]
我本地的shadowsocksX-NG 配置的是
插件: v2ray-plugin
插件选项: mux=5;path=/v2ray;tls;host=yourdomain.com;

**Comment by Acris** [comment]
运行一下`docker logs shadowsocks-libev`看看日志

**Comment by Acris** [comment]
有两个地方需要确认下：
- 确保证书是否签发成功，并正确挂载到容器内；
- docker-compose.yml加上一行`user: root`，确保有读取证书的权限，可以参考最新的README。

**Comment by neo-no93** [comment]
我把你那个dockerfile 里的nobody给注掉, 然后自己打得包, logs里显示都正常, 容器也起来了

**Comment by neo-no93** [comment]
```
version: "3.3"
services:
  shadowsocks-libev:
    container_name: shadowsocks-libev
    image: acrisliu/shadowsocks-libev-root:latest
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    privileged: true
    volumes:
      - /root/.acme.sh:/root/.acme.sh:ro
    environment:
      - PASSWORD=1993
      - ARGS=--plugin v2ray-plugin --plugin-opts server;tls;host=xxx.club;path=/v2ray;cert=/root/.acme.sh/xxx.club/fullchain.cer;key=/root/.acme.sh/xxx.club/xxx.club.key -u
    restart: always
```
