### ISSUE TITLE
Docker compose mount volume is empty

### ISSUE THREAD

**Issue by KHN190** [Acris/docker-shadowsocks-libev#38]
I have the config file as:

```yaml
version: "3.7"
services:
  shadowsocks-libev:
    container_name: shadowsocks-libev
    image: acrisliu/shadowsocks-libev:latest
    user: root
    #...
    volumes:
      - /etc/letsencrypt/live/mysite:/root/certs:ro # !!
    #...
      - ARGS=--plugin v2ray-plugin --plugin-opts server;tls;host=mysite;path=/v2ray;cert=/root/certs/fullchain.pem;key=/root/certs/privkey.pem -u
```

The container has nothing in `/root/certs`. Run docker directly from command line also mounts an empty directory:

```bash
docker run \
-e "ARGS=--plugin v2ray-plugin --plugin-opts server;tls;host=mysite;path=/v2ray;cert=/root/certs/fullchain.pem;key=/root/certs/privkey.pem -u" \
-e PASSWORD=verysecurepassword \
-v /etc/letsencrypt/live/mysite:/root/certs \ # ??
--user root \
--name=shadowsocks-libev \
-p 8388:8388/tcp \
-p 8388:8388/udp \
acrisliu/shadowsocks-libev
```

But after the container's built, I can create a debug image locally and mount the volume with:

```bash
docker ps -a # read the container hash
docker commit container_hash debug/ss
docker run -it --rm --entrypoint sh -v /etc/letsencrypt/live/mysite:/mysite debug/ss
```

And see the cert in `/mysite`. How do I make it work for docker-compose.yml? I don't see any difference.
