### ISSUE TITLE
Questions about adding V2ray plugin from noob

### ISSUE THREAD

**Issue by KinseyWang** [Acris/docker-shadowsocks-libev#6]
I see following codes, but what do "yourdomain.com" and "YourPassword" mean? is this my ss server ip address and password? or the v2ray server address and password?

docker run -d \
-e "ARGS=--plugin v2ray-plugin --plugin-opts server;tls;host=yourdomain.com -u" \
-e PASSWORD=YourPassword \
-v /home/username/.acme.sh:/root/.acme.sh \
--name=shadowsocks-libev \
-p 8388:8388/tcp \
-p 8388:8388/udp \
--restart=always \
acrisliu/shadowsocks-libev

And how to use docker-compose? sorry for the questions you might think it's stupid...I don't know all of this until today...

**Comment by Acris** [comment]
v2ray-plugin is a SIP003 plugin for shadowsocks, based on v2ray, for more detail you can see https://github.com/shadowsocks/v2ray-plugin.

To use docker-compose, install it from https://docs.docker.com/compose/install/, then use the following docker-compose.yml file:
```yaml
version: "3.7"
services:
  shadowsocks-libev:
    container_name: shadowsocks-libev
    image: acrisliu/shadowsocks-libev:latest
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    volumes:
      - /root/.acme.sh:/root/.acme.sh:ro
    environment:
      - PASSWORD=YourPassword
      - ARGS=--plugin v2ray-plugin --plugin-opts server;tls;host=yourdomain.com;path=/v2ray;cert=/root/.acme.sh/yourdomain.com/yourdomain.com.cer;key=/root/.acme.sh/yourdomain.com/yourdomain.com.key -u
    restart: always
```

Then use `docker-compose up -d` to create and start the container.
